import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import logo from "../public/image.jpg";
import {
  MdOutlineSpaceDashboard,
  MdOutlineAnalytics,
  MdOutlineIntegrationInstructions,
  MdOutlineMoreHoriz,
  MdOutlineSettings,
  MdOutlineLogout,
} from "react-icons/md";
import { CgProfile } from "react-icons/cg";
import { FaRegComments } from "react-icons/fa";
import { BiMessageSquareDots } from "react-icons/bi";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="navbar bg-base-100 fixed  z-10 px-10">
            <div className="flex-1">
              <h2 className="btn btn-ghost text-xl uppercase bg-black"></h2>
            </div>
            <div className="flex-none gap-2">
              <div className="form-control">
                <input
                  type="text"
                  placeholder="Search"
                  className="input input-bordered w-24 md:w-auto"
                />
              </div>
              <div className="dropdown dropdown-end">
                <div
                  tabIndex={0}
                  role="button"
                  className="btn btn-ghost btn-circle avatar"
                >
                  <div className="w-10 rounded-full">
                    <Image
                      alt="Tailwind CSS Navbar component"
                      src={logo}
                      width={50}
                      height={50}
                    />
                  </div>
                </div>
                <ul
                  tabIndex={0}
                  className="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-52"
                >
                  <li>
                    <a className="justify-between">
                      Profile
                      <span className="badge">New</span>
                    </a>
                  </li>
                  <li>
                    <a>Settings</a>
                  </li>
                  <li>
                    <a>Logout</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <main className="flex gap-5">
          <div className="py-6 px-4  fixed  bg-white z-20 top-0 left- lg:left-0 lg:w-60 peer:transition ease-out delay-150 duration-200">
            <div className="flex flex-col justify-start item-center  h-fit">
              <h1 className="text-base text-center cursor-pointer font-bold text-blue-900 border-b border-gray-100 pb-4 w-full">
                AH Dashboard
              </h1>
              <div className=" my-4 border-b border-gray-100 pb-4">
                <Link href="/">
                  <div className="flex mb-2 justify-start items-center gap-4 pl-5 hover:bg-gray-600 p-2 rounded-md group cursor-pointer hover:shadow-lg m-auto">
                    <MdOutlineSpaceDashboard className="text-2xl text-gray-600 group-hover:text-white " />
                    <h3 className="text-base text-gray-800 group-hover:text-white font-semibold ">
                      Dashboard
                    </h3>
                  </div>
                </Link>
                <Link href="/profile">
                  <div className="flex  mb-2 justify-start items-center gap-4 pl-5 hover:bg-gray-600 p-2 rounded-md group cursor-pointer hover:shadow-lg m-auto">
                    <CgProfile className="text-2xl text-gray-600 group-hover:text-white " />
                    <h3 className="text-base text-gray-800 group-hover:text-white font-semibold ">
                      Profile
                    </h3>
                  </div>
                </Link>
                <Link href="/comments">
                  <div className="flex  mb-2 justify-start items-center gap-4 pl-5 hover:bg-gray-600 p-2 rounded-md group cursor-pointer hover:shadow-lg m-auto ">
                    <FaRegComments className="text-2xl text-gray-600 group-hover:text-white " />
                    <h3 className="text-base text-gray-800 group-hover:text-white font-semibold pr-10">
                      Comments
                    </h3>
                  </div>
                </Link>
                <Link href="/analytics">
                  <div className="flex  mb-2 justify-start items-center gap-4 pl-5 hover:bg-gray-600 p-2 rounded-md group cursor-pointer hover:shadow-lg m-auto">
                    <MdOutlineAnalytics className="text-2xl text-gray-600 group-hover:text-white " />
                    <h3 className="text-base text-gray-800 group-hover:text-white font-semibold ">
                      Analytics
                    </h3>
                  </div>
                </Link>
                <Link href="/message">
                  <div className="flex  mb-2 justify-start items-center gap-4 pl-5 hover:bg-gray-600 p-2 rounded-md group cursor-pointer hover:shadow-lg m-auto">
                    <BiMessageSquareDots className="text-2xl text-gray-600 group-hover:text-white " />
                    <h3 className="text-base text-gray-800 group-hover:text-white font-semibold ">
                      Messages
                    </h3>
                  </div>
                </Link>
                <div className="flex  mb-2 justify-start items-center gap-4 pl-5 hover:bg-gray-600 p-2 rounded-md group cursor-pointer hover:shadow-lg m-auto">
                  <MdOutlineIntegrationInstructions className="text-2xl text-gray-600 group-hover:text-white " />
                  <h3 className="text-base text-gray-800 group-hover:text-white font-semibold ">
                    Integration
                  </h3>
                </div>
              </div>
              {/* setting  */}
              <div className=" my-2 border-b border-gray-100 pb-2">
                <div className="flex mb-2 justify-start items-center gap-4 pl-5 hover:bg-gray-600 p-2 rounded-md group cursor-pointer hover:shadow-lg m-auto">
                  <MdOutlineSettings className="text-2xl text-gray-600 group-hover:text-white " />
                  <h3 className="text-base text-gray-800 group-hover:text-white font-semibold ">
                    Settings
                  </h3>
                </div>
                <div className="flex mb-2 justify-start items-center gap-4 pl-5 hover:bg-gray-600 p-2 rounded-md group cursor-pointer hover:shadow-lg m-auto">
                  <MdOutlineMoreHoriz className="text-2xl text-gray-600 group-hover:text-white " />
                  <h3 className="text-base text-gray-800 group-hover:text-white font-semibold ">
                    More
                  </h3>
                </div>
              </div>
              {/* logout */}
              <div className=" my-4">
                <div className="flex mb-2 justify-start items-center gap-4 pl-5 border border-gray-200  hover:bg-gray-600 p-2 rounded-md group cursor-pointer hover:shadow-lg m-auto">
                  <MdOutlineLogout className="text-2xl text-gray-600 group-hover:text-white " />
                  <h3 className="text-base text-gray-800 group-hover:text-white font-semibold ">
                    Logout
                  </h3>
                </div>
              </div>
            </div>
          </div>

          <div className=" mx-auto my-20">{children}</div>
        </main>
      </body>
    </html>
  );
}
